input.onButtonPressed(Button.A, function () {
    basic.pause(500)
    servos.P1.setAngle(0)
    basic.showNumber(0)
    basic.pause(500)
    servos.P1.setAngle(90)
    basic.showNumber(90)
    basic.pause(500)
    servos.P1.setAngle(180)
    basic.showNumber(180)
    servos.P1.stop()
    servos.P1.run(100)
})
input.onButtonPressed(Button.AB, function () {
    servos.P1.stop()
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 100; index++) {
        servos.P1.run(100)
        servos.P1.setAngle(0)
        servos.P1.setAngle(15)
        servos.P1.setAngle(30)
        servos.P1.setAngle(45)
        servos.P1.setAngle(60)
        servos.P1.setAngle(75)
        servos.P1.setAngle(90)
        servos.P1.setAngle(105)
        servos.P1.setAngle(120)
        servos.P1.setAngle(135)
        servos.P1.setAngle(150)
        servos.P1.setAngle(165)
        servos.P1.setAngle(180)
    }
})
basic.showString("servo time", 65)
basic.showIcon(IconNames.Heart)
